name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install gcc libasound2-dev
      run: sudo apt-get install -y gcc libasound2-dev
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    #- name: Run tests
    #  run: cargo test --verbose
